uriparser/uriparser

- ChangeLog
- THANKS
- src/UriFile.c
- test/test.cpp
PS: @vs49688 I'm happy to put your real name in for credit instead, if that's something you're willing to share.
> Proposed fix for issue #12

- .travis.yml
- CMakeLists.txt
- ChangeLog
- appveyor.yml
- include/uriparser/Uri.h
- include/uriparser/UriBase.h
- include/uriparser/UriIp4.h
- src/UriQuery.c
Regarding the work-in-progress aspect / current CI failure: https://github.com/google/sanitizers/wiki/AddressSanitizerOneDefinitionRuleViolation
@myd7349 @KangLin review and testing very welcome, thank you!
> Symbol visibility

- ChangeLog
- include/uriparser/Uri.h
- src/UriNormalize.c
- test/test.cpp
For #77
@veselov this is a first rough version. API docs are yet to come, formatting might change, function names might change. Would be great to have your review on this. Thanks!
> Support making UriUri* instance independent (for #77)

- liburiparser.pc.in
This also removes issues when cross-compiling for example in OpenWrt.
> pkg-config: improve template to be more generic

- ChangeLog
- THANKS
- src/UriCommon.c
- src/UriCommon.h
- test/test.cpp
> Fix RemoveDotSegmentsEx for URIs like "http://a/.." (fixes #92)

- ChangeLog
- doc/Mainpage.txt
> docs: Use pkg-config for detection in configure.ac (fixes #37)

- ChangeLog
- test/MemoryManagerSuite.cpp
> tests: Add missing 'extern "C"'

- CMakeLists.txt
- ChangeLog
- include/uriparser/Uri.h
- include/uriparser/UriBase.h
> Prepare release 0.9.5

- CMakeLists.txt
- ChangeLog
- THANKS
- appveyor.yml
@arichardson in a sense I'm putting words/commits into your mouth here so it would be awesome if you had a second for review to be sure you don't feel misrepresented after. Thanks!
CC https://github.com/libexpat/libexpat/pull/442#issuecomment-802208332
> CMake: Only set CMAKE_CXX_FLAGS after enable_language(CXX)

- .github/workflows/build-and-test.yml
- CMakeLists.txt
- ChangeLog
- cmake/test_find_package/.gitignore
- make-distcheck.sh
- test/test.cpp
- tool/uriparse.c
> [MinGW] Cover MinGW in CI (#39) + fix MinGW compilation (#117)

- .github/workflows/build-and-test.yml
CC https://github.com/actions/virtual-environments/issues/4589
> Actions: Workaround libwine:i386 installation issues

- ChangeLog
- THANKS
- include/uriparser/UriBase.h
> Fix symbol visibility for non-MSVC static library build (fixes #139)

- .github/workflows/build-and-test.yml
> Actions: Make MinGW with 32bit Wine on Ubuntu 20.04 possible

- .github/workflows/build-and-test.yml
> Actions: Sync libwine:i386 conflict resolution code

- CMakeLists.txt
- ChangeLog
- THANKS
- include/uriparser/Uri.h
- include/uriparser/UriBase.h
> Prepare release 0.9.7 (part of #153)

- ChangeLog
- include/uriparser/Uri.h
> Document user responsibility regarding scheme-based normalization (fixes #173)

- ChangeLog
- include/uriparser/Uri.h
> Document supported code points for escape (fixes #171)

- doc/preprocess.sh
> `doc/preprocess.sh`: Make `Mainpage.txt` bypass the C preprocessor (fixes #226)

- .github/workflows/fuzzing.yml
> `fuzzing.yml`: Start fuzzing wide string corpora, too

- src/UriCopy.c
- src/UriNormalize.c
> src: Rename variable `doneMask` to `revertMask` (fixes #233)

- .github/workflows/build-and-test.yml
- .github/workflows/codespell.yml
- ChangeLog
- doc/Doxyfile.in
- include/uriparser/Uri.h
- include/uriparser/UriBase.h
- src/UriCommon.c
- test/FourSuite.cpp
> Codespell fixes and CI

- ChangeLog
- THANKS
- src/UriCommon.c
- test/test.cpp
Fixes #262, alternative to #263
CC @TimWolla
> Fix syntax-based URI normalization (fixes #262, alternative to #263)
