uriparser/uriparser

- src/UriShorten.c
> UriRemoveBaseUri: Fix bad usage of URI_STRNCMP (#19)

- configure.ac
Haiku fails the build when not linked against -lsocket/-lnetwork, this would reduce the need of creating a patch for Haiku and shouldn't affect other OS's
> Fix Haiku build, link to -lsocket for inet_ntop

- win32/Visual_Studio_2005/uriparser.vcproj
Uriparser will compile w/o error, but the linker will throw unresolved external symbol errors when you go to actually use the library.
> Fix VS2005 Build, UriMemory.c, UriMemory.h missing from project

- CMakeLists.txt
Currently, the shared lib build on Win32 doesn't work properly:
1. The generated DLL file exports no symbols, so a corresponding export lib will not be created. And the user of this lib has nothing to link to. This issue can be resolved by setting `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`: https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html
2. The generated DLL file installed to a wrong path. It is similar to: https://stackoverflow.com/questions/22278381/cmake-add-library-followed-by-install-library-destination
> cmake: Fix dll install path on Win32

- CMakeLists.txt
for use when bundling uriparser as a static lib, provide a way to optionally turn off installation of files.  the default is behavior of the option is set to on
> Add option to enable/disable installation of files, default is enabled (#74)

- CMakeLists.txt
> CMake: Use GTEST_INCLUDE_DIRS (plural) not GTEST_INCLUDE_DIR (singular) (for #79)

- doc/Mainpage.txt
old version number in text, but not in autoconf code
> @section autoconf Autoconf Check

- CMakeLists.txt
https://github.com/uriparser/uriparser/pull/64 changed not only dll name but also name of static lib, which lead to wrong extension.
This PR fixes extension for static lib with MinGW, while keeping version suffix in dll name.
> cmake: fix static lib name for MinGW

- CMakeLists.txt
- ChangeLog
> CMakeLists.txt: Link against pthreads for -DURIPARSER_BUILD_TESTS=ON (fixes #99)

- CMakeLists.txt
When the prefix is missing, installing `uriparser` from dependent projects causes issues as the files before relative to the parent directories.
This should fix that by using absolute paths from the prefix.
> Add CMAKE_CURRENT_SOURCE_DIR prefix to sources

- .github/workflows/build-and-test.yml
In reaction to https://github.com/uriparser/uriparser/runs/2092156827?check_suite_focus=true caused by `ubuntu-latest` jumping from bionic/18.04.x to focal/20.04.x…
> Migrate CI to Qt 5

- CMakeLists.txt
- ChangeLog
- THANKS
- liburiparser.pc.in
Related to https://github.com/libexpat/libexpat/pull/459
CC @rffontenelle
> CMake: Support absolute paths for CMAKE_INSTALL_(LIB|INCLUDE)DIR

- ChangeLog
- include/uriparser/Uri.h
> Doc: Fix space requirements of uriUriStringToUnixFilename (fixes #118)

- src/UriMemory.c
Fix implicit declaration warning of function reallocarray on NetBSD.
> Fix implicit declaration warning for reallocarray on NetBSD

- tool/uriparse.c
From a patch from msys2, `/usr/x86_64-w64-mingw32/include/_mingw.h` defines `_WIN32_WINNT` on mingw-w64 cross compilers
> uriparse: use size_t for inet_ntop declaration and fix macro checks for MinGW and mingw-w64

- .github/workflows/build-and-test.yml
Error was:
```
[..]
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
wine32:i386 : Depends: libwine:i386 (= 5.0-3ubuntu1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Related to #127
> Actions: Address "held broken packages" issue

- .gitignore
- CMakeLists.txt
- src/UriMemory.c
- test/VersionSuite.cpp
This guard makes it possible to build the entire project without a config.h file, instead all the preprocessor definitions can be provided from the command line.
In my case, we build the entire library by including all `.c` files in a single `.c` file with all the needed definitions, thus simplifying the build process:
in `liburiparser.c`
```
#define URI_CONFIG_H 1
#define PACKAGE_VERSION "0.9.6"
#define HAVE_WPRINTF
#include "uriparser/src/UriCommon.c"
#include "uriparser/src/UriCompare.c"
#include "uriparser/src/UriEscape.c"
#include "uriparser/src/UriFile.c"
#include "uriparser/src/UriIp4.c"
#include "uriparser/src/UriIp4Base.c"
#include "uriparser/src/UriMemory.c"
#include "uriparser/src/UriNormalize.c"
#include "uriparser/src/UriNormalizeBase.c"
#include "uriparser/src/UriParse.c" …
```
> Include config.h only when it has not already been defined

- src/UriParse.c
- test/FourSuite.cpp
- test/test.cpp
Closes #146. This is ready for review now. @hartwork
I've added several test cases for the issue and can confirm that all the five bugs listed in #146 are fixed.
> Fix IPv6 and IPvFuture literal parsing

- .github/workflows/build-and-test.yml
Symptom was:
> /usr/bin/ld: cannot find /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.asan_static-x86_64.a: No such file or directory
> /usr/bin/ld: cannot find /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.asan-x86_64.a: No such file or directory
Related:
https://github.com/llvm/llvm-project/issues/60008
> Actions: Make sure that AddressSanitizer files are always available

- CMakeLists.txt
- ChangeLog
- README.md
.. that mimics flag `BUILD_SHARED_LIBS` and falls back to `BUILD_SHARED_LIBS` if available, else defaults to `ON`.
Related:
https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html
Fixes #169
> CMake: Introduce option `URIPARSER_SHARED_LIBS=(ON|OFF)` (fixes #169)

- .github/workflows/build-and-test.yml
- CMakeLists.txt
- ChangeLog
- README.md
- cmake/test_find_package/CMakeLists.txt
Related CMake error was:
> CMake Deprecation Error at CMakeLists.txt:37 (cmake_minimum_required):
>   Compatibility with CMake < 3.5 will be removed from a future version of
>   CMake.
>
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> Require CMake >=3.5.0

- src/UriQuery.c
Requires string input that is longer than `INT_MAX` to exploit.
Related to issue #183
> Protect against integer overflow in `ComposeQueryEngine` (related to #183)

- src/UriQuery.c
Requires string input that is longer than `INT_MAX / 6 - 1` to exploit.
Related to issue #183
> Protect against integer overflow in `ComposeQueryMallocExMm` (related to #183)

- CMakeLists.txt
uriparser is exported as uriparser::uriparser so I added this alias here also. Otherwise devs would have to differentiate if they found the lib with find_package or are chainbuilding with i.e. fetchcontent
> Add alias uriparser::uriparser

- .github/workflows/build-and-test.yml
There is no package `debsuryorg-archive-keyring` in Ubuntu `focal`, so it has to be excluded from the list of packages that are reverted back to Ubuntu focal.
Symptom was:
```console
debsuryorg-archive-keyring/focal libgd3:amd64/focal libhashkit2:amd64/focal \
libmemcached11:amd64/focal libpcre2-16-0:amd64/focal libpcre2-32-0:amd64/focal \
libpcre2-8-0:amd64/focal
Reading package lists...
Building dependency tree...
Reading state information...
E: Release 'focal' for 'debsuryorg-archive-keyring' was not found
```
> Fix CI / `build-and-test.yml`: Fix mishandling of package `debsuryorg-archive-keyring`

- CMakeLists.txt
- cmake/test_find_package/CMakeLists.txt
.. to address this CMake warning:
```
CMake Deprecation Error at CMakeLists.txt:37 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <minvalue or use a ...<maxsuffix to tell
CMake that the project does not need compatibility with older versions.
```
> Fix CI / Require CMake >=3.10.0

- include/uriparser/Uri.h
.. in that they escape all characters *but* the unreserved ones, instead of *just* the unreserved ones.
Fixes #206
> Fix documentation of `uriEscape*` family of functions (fixes #206)

- fuzz/FuzzingUtils.h
Adjustment after https://github.com/uriparser/uriparser/pull/209
```
[ 75%] Building CXX object CMakeFiles/uri_dissect_query_malloc_fuzzer.dir/fuzz/DissectQueryMallocFuzzer.cpp.o
In file included from /src/uriparser/fuzz/DissectQueryMallocFuzzer.cpp:17:
/src/uriparser/fuzz/FuzzingUtils.h:41:27: error: no matching member function for call to 'ConsumeIntegralInRange'
41 |         const size_t chars = fdp.ConsumeIntegralInRange(0ul, max_chars);
|                              ~~~~^~~~~~~~~~~~~~~~~~~~~~
/usr/local/lib/clang/18/include/fuzzer/FuzzedDataProvider.h:204:23: note: candidate template ignored: deduced conflicting types for parameter 'T' ('unsigned long' vs. 'size_t' (aka 'unsigned int'))
204 | T FuzzedDataProvider::ConsumeIntegralInRange(T min, T max) {
|                       ^
1 …
```
> Fix fuzzers build for i386 architecture

- fuzz/ParseFuzzer.cpp
- Reported: `Mon, Jan 13, 2025, 1:03 PM`
- OSS-Fuzz issue: https://issues.oss-fuzz.com/issues/389731913
- Detailed Report: https://oss-fuzz.com/testcase?key=6067233314373632
- Regressed: https://oss-fuzz.com/revisions?job=libfuzzer_ubsan_uriparser&range=202501060601:202501070634
- Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=6067233314373632
CC @tyler92
> `fuzz/ParseFuzzer.cpp`: Fix `maxChars` input for call to `uriToStringW`

- src/UriNormalize.c
- test/test.cpp
A simple solution that skips lowercasing 2 characters after each `%`.
Fixes #221
> Normalized percent-encoded octets should have uppercase letters in the host (fixes #221)

- CMakeLists.txt
> cmake: Compile with `-std=c90` by default

- test/VersionSuite.cpp
- test/test.cpp
Related to review comments in #230, e.g. https://github.com/uriparser/uriparser/pull/230#discussion_r2170209568 .
Notable exceptions (i.e. the only known leftovers) for now:
- `ASSERT_TRUE(.* == NULL);`
- `ASSERT_TRUE(.* != NULL);`
Both [would need `nullptr` rather than `NULL` to work](https://google.github.io/googletest/reference/assertions.html#EXPECT_EQ) but [`nullptr` requires C++11](https://en.cppreference.com/w/cpp/language/nullptr.html) while the current code uses C++98 to this date.
CC @kocsismate
> tests: Mass-replace `ASSERT_TRUE([..] == [..])` by `ASSERT_EQ`

- include/uriparser/Uri.h
- src/UriCommon.c
- src/UriCommon.h
- src/UriRecompose.c
- src/UriResolve.c
I need this function for prepending the `/` to the path component when the relevant getter is used (https://github.com/php/php-src/pull/18836/files#diff-04ea97756e1ce310ccfd4d8775089274da9a7ce11af774336dbda793e6642fcbR197):
```
if (uriparser_uri->absolutePath || uriIsHostSetA(uriparser_uri)) {
smart_str_appendc(&str, '/');
}
...
```
> Add function `HasHost` to the public API

- CMakeLists.txt
- include/uriparser/Uri.h
- src/UriCommon.c
- src/UriCommon.h
- src/UriCopy.c
- src/UriCopy.h
- src/UriNormalize.c
- src/UriNormalize.h
- test/copy.cpp
I also need this functionality for https://wiki.php.net/rfc/url_parsing_api because of multiple reasons:
- In order to maintain immutability of URIs, the structs have to be copied first before any modification
- The PHP `Uri` class exposes both the normalized and non-normalized URI components (therefore it internally stores two Uri structs). When a normalized component is requested, normalization is done on demand, by copying the original struct first
The patch needs a last few touches, including tests, but I wanted to propose it nevertheless to get early feedback.
> Fix #200 Add support for copying Uri structures

- include/uriparser/Uri.h
- test/test.cpp
> tests: Cover `FreeUriMembers` after `memset` with zeros (fixes #238)

- src/UriCopy.c
- test/copy.cpp
When trying to copy a URI with empty userInfo, portText, query, or fragment components, the copying process would perform a zero-byte allocation for the respective component.
Depending on the malloc implementation, this would either return `NULL`, leading to a bogus `URI_ERROR_MALLOC` being returned from the copying process or a valid zero-byte allocation that will not be freed by FreeUriMembers, resulting in a memory leak.
> src/UriCopy.c: Fix copying URIs with empty components

- include/uriparser/UriIp4.h
> Fix docstring typo in `ParseIpFourAddress`

- src/UriParse.c
In reaction to https://github.com/uriparser/uriparser/pull/249#discussion_r2312063320 …
Pointer arithmetic beyond the end (one after the last) of the array even without dereferencing is undefined behavior.
Affected functions are:
- `ParseIpFuture`
- `ParseIPv6address2`
- `ParsePctEncoded`
CC @TimWolla
> `src/UriParse.c`: Dissolve undefined behavior

- CMakeLists.txt
- include/uriparser/Uri.h
- include/uriparser/UriBase.h
- src/UriVersion.c
- test/VersionSuite.cpp
Fixes #219
In reaction to https://github.com/uriparser/uriparser/pull/256#issuecomment-3247991741
CC @TimWolla @FromeXo
> Add function `BaseRuntimeVersion` + fix `URI_VER*_UNICODE` macros (fixes #219)

- src/UriCommon.c
- test/test.cpp
Fixes uriparser/uriparser#262.
> UriCommon.c: Do not remove leading `/./` segment when followed by empty segment
